const config = {
    Project_Id :import.meta.env.VITE_PROJECT_ID,
    DATABASE_ID: import.meta.env.VITE_DATABASE_ID,
    PROJECT_COLLECTION_TABLE: import.meta.env.VITE_PROJECT_COLLECTION_TABLE,
    ABOUT_SECTION_COLLECTION_TABLE: import.meta.env.VITE_ABOUT_SECTION_COLLECTION_TABLE,
    SKILLS_COLLECTION_TABLE: import.meta.env.VITE_SKILLS_COLLECTION_TABLE,
    STORAGE_FOR_ABOUT_SECTION: import.meta.env.VITE_STORAGE_FOR_ABOUT_SECTION,
    STORAGE_FOR_PROJECT_SECTION: import.meta.env.VITE_STORAGE_FOR_PROJECT_SECTION,
    PEOPLE_MESSAGES_COLLECTION: import.meta.env.VITE_PEOPLE_MESSAGES_COLLECTION,
    TINYMCE_EDITOR_APIKEY: String(import.meta.env.VITE_TINYMCE_EDITOR_APIKEY)
  };
  
  export default config;
  